import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBowlFood, faEgg, faCarrot, faBurger, faMugHot, faLemon, faFish, faShrimp, faPizzaSlice, faPepperHot, faIceCream, faHotdog, faGlassWater, faDrumstickBite, faCookie, faCheese, faCakeCandles, faBowlRice } from '@fortawesome/free-solid-svg-icons'

const icons = [
    { icon: <FontAwesomeIcon icon={faBowlFood} />, color: '#F4CBDF' },
    { icon: <FontAwesomeIcon icon={faEgg} />, color: '#CDDFEC' },
    { icon: <FontAwesomeIcon icon={faCarrot} />, color: '#E7DEE3' },
    { icon: <FontAwesomeIcon icon={faBurger} />, color: '#D1D1EF' },
    { icon: <FontAwesomeIcon icon={faMugHot} />, color: '#D0EAE3' },
    { icon: <FontAwesomeIcon icon={faLemon} />, color: '#F4CBDF' },
    { icon: <FontAwesomeIcon icon={faFish} />, color: '#CDDFEC' },
    { icon: <FontAwesomeIcon icon={faShrimp} />, color: '#E7DEE3' },
    { icon: <FontAwesomeIcon icon={faPizzaSlice} />, color: '#CDDFEC' },
    { icon: <FontAwesomeIcon icon={faPepperHot} />, color: '#F4CBDF' },
    { icon: <FontAwesomeIcon icon={faIceCream} />, color: '#E7DEE3' },
    { icon: <FontAwesomeIcon icon={faHotdog} />, color: '#CDDFEC' },
    { icon: <FontAwesomeIcon icon={faGlassWater} />, color: '#F4CBDF' },
    { icon: <FontAwesomeIcon icon={faDrumstickBite} />, color: '#E7DEE3' },
    { icon: <FontAwesomeIcon icon={faCookie} />, color: '#D1D1EF' },
    { icon: <FontAwesomeIcon icon={faCheese} />, color: '#CDDFEC' },
    { icon: <FontAwesomeIcon icon={faCakeCandles} />, color: '#D1D1EF' },
    { icon: <FontAwesomeIcon icon={faBowlRice} />, color: '#F4CBDF' },
    { icon: <FontAwesomeIcon icon={faBowlFood} />, color: '#E7DEE3' },
    { icon: <FontAwesomeIcon icon={faEgg} />, color: '#D1D1EF' },
    { icon: <FontAwesomeIcon icon={faCarrot} />, color: '#CDDFEC' },
    { icon: <FontAwesomeIcon icon={faBurger} />, color: '#D1D1EF' },
    { icon: <FontAwesomeIcon icon={faMugHot} />, color: '#F4CBDF' },
    { icon: <FontAwesomeIcon icon={faLemon} />, color: '#D1D1EF' },
    { icon: <FontAwesomeIcon icon={faFish} />, color: '#CDDFEC' },
    { icon: <FontAwesomeIcon icon={faShrimp} />, color: '#E7DEE3' },
    { icon: <FontAwesomeIcon icon={faPizzaSlice} />, color: '#D1D1EF' },
    { icon: <FontAwesomeIcon icon={faPepperHot} />, color: '#F4CBDF' },
    { icon: <FontAwesomeIcon icon={faPepperHot} />, color: '#D1D1EF' },
    { icon: <FontAwesomeIcon icon={faIceCream} />, color: '#CDDFEC' },
    { icon: <FontAwesomeIcon icon={faHotdog} />, color: '#F4CBDF' },
    { icon: <FontAwesomeIcon icon={faGlassWater} />, color: '#E7DEE3' },
    { icon: <FontAwesomeIcon icon={faDrumstickBite} />, color: '#D1D1EF' },
    { icon: <FontAwesomeIcon icon={faCookie} />, color: '#CDDFEC' },
    { icon: <FontAwesomeIcon icon={faCheese} />, color: '#D1D1EF' },
    { icon: <FontAwesomeIcon icon={faCakeCandles} />, color: '#F4CBDF' },
    { icon: <FontAwesomeIcon icon={faBowlRice} />, color: '#D1D1EF' },
    { icon: <FontAwesomeIcon icon={faBowlFood} />, color: '#CDDFEC' },
    { icon: <FontAwesomeIcon icon={faEgg} />, color: '#F4CBDF' },
    { icon: <FontAwesomeIcon icon={faCarrot} />, color: '#E7DEE3' },
    { icon: <FontAwesomeIcon icon={faBowlRice} />, color: '#D1D1EF' },
    { icon: <FontAwesomeIcon icon={faBowlFood} />, color: '#CDDFEC' },
    { icon: <FontAwesomeIcon icon={faEgg} />, color: '#F4CBDF' },
    { icon: <FontAwesomeIcon icon={faCarrot} />, color: '#CDDFEC' },
];

export default icons;